# Generated by Django 5.1 on 2025-11-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(default='basic_user', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('security_question', models.CharField(max_length=255)),
                ('security_answer', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('suffix', models.CharField(blank=True, max_length=10, null=True)),
                ('birthdate', models.DateField()),
                ('sex', models.CharField(max_length=1)),
                ('religion', models.CharField(max_length=100)),
                ('home_address', models.TextField()),
                ('contact_number', models.CharField(max_length=20)),
                ('nationality', models.CharField(default='Filipino', max_length=50)),
                ('civil_status', models.CharField(max_length=20)),
                ('educational_attainment', models.CharField(max_length=50)),
                ('employment_status', models.CharField(max_length=20)),
                ('occupation', models.CharField(max_length=100)),
                ('emergency_contact_name', models.CharField(default='N/A', max_length=200)),
                ('emergency_contact_number', models.CharField(default='0000', max_length=20)),
                ('emergency_contact_address', models.TextField(default='N/A')),
                ('valid_id_path', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
