# Generated by Django 5.1 on 2025-11-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fingerprint_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
