# Generated by Django 5.1 on 2025-11-25 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PWDProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=9, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('suffix', models.CharField(blank=True, max_length=10, null=True)),
                ('birthdate', models.DateField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('civil_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Divorced', 'Divorced'), ('Separated', 'Separated')], max_length=20)),
                ('barangay', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=20)),
                ('religion', models.CharField(default='N/A', max_length=100)),
                ('nationality', models.CharField(default='Filipino', max_length=50)),
                ('photo_path', models.CharField(blank=True, max_length=255, null=True)),
                ('educational_attainment', models.CharField(choices=[('None', 'None'), ('Elementary', 'Elementary'), ('High School', 'High School'), ('College', 'College'), ('Vocational', 'Vocational'), ('College Graduate', 'College Graduate'), ('Masters', 'Masters'), ('Doctorate', 'Doctorate')], max_length=50)),
                ('employment_status', models.CharField(choices=[('Employed', 'Employed'), ('Unemployed', 'Unemployed'), ('Self-Employed', 'Self-Employed'), ('Student', 'Student'), ('Retired', 'Retired')], max_length=20)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('type_of_employment', models.CharField(blank=True, choices=[('', ''), ('Permanent', 'Permanent'), ('Contractual', 'Contractual'), ('Casual', 'Casual'), ('Part-time', 'Part-time'), ('Self-employed', 'Self-employed')], max_length=50, null=True)),
                ('household_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('household_size', models.IntegerField(blank=True, null=True)),
                ('living_situation', models.CharField(blank=True, choices=[('', ''), ('Living Alone', 'Living Alone'), ('Living with Family', 'Living with Family'), ('Living with Relatives', 'Living with Relatives'), ('Living with Friends', 'Living with Friends'), ('Institution', 'Institution')], max_length=50, null=True)),
                ('housing_type', models.CharField(blank=True, choices=[('', ''), ('Owned', 'Owned'), ('Rented', 'Rented'), ('Shared', 'Shared'), ('Informal Settler', 'Informal Settler')], max_length=50, null=True)),
                ('guardian_name', models.CharField(default='N/A', max_length=200)),
                ('guardian_contact', models.CharField(default='0000', max_length=20)),
                ('disability_type', models.CharField(choices=[('Visual', 'Visual Disability'), ('Hearing', 'Hearing Disability'), ('Speech', 'Speech Disability'), ('Physical', 'Physical Disability'), ('Mental', 'Mental Disability'), ('Intellectual', 'Intellectual Disability'), ('Learning', 'Learning Disability'), ('Psychosocial', 'Psychosocial Disability'), ('Multiple', 'Multiple Disabilities')], max_length=100)),
                ('degree_of_disability', models.CharField(choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High')], max_length=20)),
                ('cause_of_disability', models.CharField(blank=True, choices=[('', ''), ('Congenital', 'Congenital/Birth'), ('Illness', 'Illness'), ('Accident', 'Accident'), ('Age', 'Age-related'), ('Other', 'Other')], max_length=100, null=True)),
                ('date_diagnosed', models.DateField(blank=True, null=True)),
                ('assistive_devices', models.TextField(blank=True, null=True)),
                ('medication', models.TextField(blank=True, null=True)),
                ('philhealth_number', models.CharField(blank=True, max_length=20, null=True)),
                ('sss_gsis_number', models.CharField(blank=True, max_length=20, null=True)),
                ('skills_hobbies', models.TextField(blank=True, null=True)),
                ('organization_membership', models.TextField(blank=True, null=True)),
                ('emergency_contact_name', models.CharField(default='N/A', max_length=200)),
                ('emergency_contact_number', models.CharField(default='0000', max_length=20)),
                ('emergency_contact_address', models.TextField(default='N/A')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pwd_created', to='accounts.user')),
                ('updated_by', models.ForeignKey(db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pwd_updated', to='accounts.user')),
            ],
            options={
                'db_table': 'pwd_profile',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PWDDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(default='pdf', max_length=10)),
                ('file_size', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(db_column='uploaded_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pwd_documents_uploaded', to='accounts.user')),
                ('pwd_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='pwd.pwdprofile')),
            ],
            options={
                'db_table': 'pwd_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
