# Generated by Django 5.1 on 2025-12-03 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwd', '0002_pwdprofile_fingerprint_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pwdprofile',
            name='fingerprint_slot',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
