# Generated by Django 5.1 on 2025-12-03 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_fingerprint_id'),
        ('pwd', '0004_add_account_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pwdprofile',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pwd_account', to='accounts.user'),
        ),
    ]
