# Generated by Django 5.1 on 2025-12-06 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_fingerprint_id'),
        ('pwd', '0005_alter_pwdprofile_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='pwdprofile',
            name='pwd_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='pwdprofile',
            name='pwd_user',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AddIndex(
            model_name='pwdprofile',
            index=models.Index(fields=['unique_id'], name='pwd_profile_unique__748137_idx'),
        ),
        migrations.AddIndex(
            model_name='pwdprofile',
            index=models.Index(fields=['fingerprint_id'], name='pwd_profile_fingerp_3a4497_idx'),
        ),
        migrations.AddIndex(
            model_name='pwdprofile',
            index=models.Index(fields=['fingerprint_slot'], name='pwd_profile_fingerp_71c219_idx'),
        ),
        migrations.AddIndex(
            model_name='pwdprofile',
            index=models.Index(fields=['pwd_user'], name='pwd_profile_pwd_use_0cea61_idx'),
        ),
    ]
